# Project Configuration
spring.application.name=${SKLOORA_MAIL_APP_NAME:Skloora-Mail-Service}

# Database Configuration
spring.datasource.url=${SKLOORA_MAIL_DB_URL}
spring.datasource.username=${SKLOORA_MAIL_DB_USERNAME}
spring.datasource.password=${SKLOORA_MAIL_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Mail Configuration
spring.mail.host=${SKLOORA_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SKLOORA_MAIL_PORT:587}
spring.mail.username=${SKLOORA_MAIL_USERNAME}
spring.mail.password=${SKLOORA_MAIL_PASSWORD}

# Mail Security
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
