# Project Configuration
spring.application.name=${SKLOORA_LB_APP_NAME:Skloora-Load-Balancer}

# Server Configuration
server.port=${SKLOORA_LB_PORT:9090}
server.servlet.context-path=${SKLOORA_LB_CONTEXT_PATH:/skloora}

# Servlet Configuration
spring.servlet.multipart.max-file-size=${SKLOORA_LB_MAX_FILE_SIZE:100MB}
spring.servlet.multipart.max-request-size=${SKLOORA_LB_MAX_REQUEST_SIZE:100MB}

# Thymeleaf Configuration
spring.thymeleaf.prefix=${SKLOORA_LB_THYMELEAF_PREFIX}
spring.thymeleaf.suffix=${SKLOORA_LB_THYMELEAF_SUFFIX:.html}
