spring.application.name=Skloora-Load-Balancer

server.port = 9090

#Servler Configurations
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.servlet.context-path=/skloora

#Thymeleaf Configurations
spring.thymeleaf.prefix=file:///D:/Senthil/Personal/SARAVANAKUMAR/programs/Java/Spring/Skloora/Skloora-Frontend/templates/
spring.thymeleaf.suffix=.html

