#Project Configuration
spring.application.name=Skloora
#Server Configuration
server.address=0.0.0.0
server.port=8315
server.http2.enabled=true
server.shutdown=graceful
server.servlet.context-path=/skloora
#Servlet Configurations
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#DataBase Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/JDBC
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=saravanakumar
spring.datasource.password=S@r0@2012
#Thymeleaf Configurations
spring.thymeleaf.prefix=file:///D:/Senthil/Personal/SARAVANAKUMAR/programs/Java/Spring/Skloora/Skloora-Frontend/templates/
spring.thymeleaf.suffix=.html
