# Project Configuration
spring.application.name=${SKLOORA_APP_NAME:Skloora}

# Server Configuration
server.address=${SKLOORA_SERVER_ADDRESS:0.0.0.0}
server.port=${SKLOORA_SERVER_PORT:8315}
server.http2.enabled=true
server.shutdown=graceful
server.servlet.context-path=${SKLOORA_CONTEXT_PATH:/skloora}

# Servlet Configurations
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Database Configuration
spring.datasource.url=${SKLOORA_DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SKLOORA_DB_USERNAME}
spring.datasource.password=${SKLOORA_DB_PASSWORD}

# Thymeleaf Configuration
spring.thymeleaf.prefix=${SKLOORA_THYMELEAF_PREFIX}
spring.thymeleaf.suffix=.html
