spring.application.name=Skloora-Mail-Service

#DataBase Configuration
<<<<<<< HEAD
spring.datasource.url = jdbc:postgresql://localhost:5432/JDBC
spring.datasource.username = saravanakumar
spring.datasource.password = S@r0@2012
spring.datasource.driver-class-name = org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subramanianl1947@gmail.com
spring.mail.password=agnp cksx yebd xman
=======
spring.datasource.url = ${Your_DB_URL}
spring.datasource.username = ${Your_DB_Username}
spring.datasource.password = ${Your_DB_password}
spring.datasource.driver-class-name = ${Your_DB_Driver_Class}

spring.mail.host=${Your_Main_Host}
spring.mail.port=$E{Your_Mail_Port}
spring.mail.username=${Your_Main_Username}
spring.mail.password=${Your_Email_App_Passwor}
>>>>>>> 43f612d06bc51106f5a6a8b8cdcc7ce5570bc9ec

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
