#Project Configuration
spring.application.name = Skloora

#Server Configuration
server.address = 0.0.0.0
server.port = 8315
server.http2.enabled = true
server.shutdown = graceful

#DataBase Configuration
spring.datasource.url = jdbc:postgresql://localhost:5432/JDBC
spring.datasource.username = saravanakumar
spring.datasource.password = S@r0@2012
spring.datasource.driver-class-name = org.postgresql.Driver

#Mail Configuration
spring.mail.host = smtp.gmail.com
spring.mail.port = 587
spring.mail.username = subramanianl1947@gmail.com
spring.mail.password = agnp cksx yebd xman


#Mail Properties Configuration
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true   