#Project Configuration
spring.application.name = Skloora

#Server Configuration
server.address = 0.0.0.0
server.port = 8315
server.http2.enabled = true
server.shutdown = graceful

#DataBase Configuration
spring.datasource.url = ${Your_DB_URL}
spring.datasource.username = ${Your_DB_Username}
spring.datasource.password = ${Your_DB_Password}
spring.datasource.driver-class-name = ${Your_Driver_CLass}

#Mail Configuration
spring.mail.host = ${Your_Host}
spring.mail.port = ${Your_Port_no}
spring.mail.username = ${Your_EMail}
spring.mail.password = ${Your_App_Password}


#Mail Properties Configuration
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true   
